# Generated by Django 5.0.6 on 2024-09-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_remove_playlist_songs_playlistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='linkapple',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='linkspotify',
            field=models.CharField(default='', max_length=200),
        ),
    ]
