# Generated by Django 5.0.6 on 2024-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_song_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='typee',
            field=models.CharField(default='String', max_length=200),
        ),
    ]
